apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-south-1
      auth:
        iamRolesAnywhere:
          roleArn: arn:aws:iam::891274465984:role/eso-roles-anywhere-role
          trustAnchorArn: arn:aws:rolesanywhere:ap-south-1:891274465984:trust-anchor/35020f64-9ddb-4c6c-b930-bb72826e4792
          profileArn: arn:aws:rolesanywhere:ap-south-1:891274465984:profile/9bc236bc-12ce-414b-b18c-72ce6392854c
          certificate:
            name: eso-roles-anywhere-cert
            namespace: external-secrets
            key: tls.crt
          privateKey:
            name: eso-roles-anywhere-cert
            namespace: external-secrets
            key: tls.key
