apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: banking-db-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: SecretStore
  target:
    name: banking-db-credentials
    creationPolicy: Owner
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: /production/banking-database/db_password
