# Helm values file for kube-prometheus-stack installation
# Usage: helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring -f prometheus_values.yaml

defaultRules:
  create: true
  rules:
    etcd: true
    k8s: true
    kubeApiserver: true
    kubePrometheusNodeAlerting: true
    network: true

grafana:
  enabled: true
  adminPassword: "ChangeMeInProduction123!"
  persistence:
    enabled: true
    storageClassName: "longhorn-replicated"
    size: 10Gi
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "longhorn-replicated"
          resources:
            requests:
              storage: 30Gi
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "longhorn-replicated"
          resources:
            requests:
              storage: 5Gi
