apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: microservices-secrets
  namespace: microservices
  labels:
    app.kubernetes.io/part-of: task-suite
spec:
  # Polling interval to check AWS SSM Parameter Store for credential rotation
  refreshInterval: 1h

  # Reference to the cluster-wide AWS SSM Parameter Store connector
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore

  # The native Kubernetes Secret created and managed by ESO in namespace 'microservices'
  target:
    name: microservices-secrets
    creationPolicy: Owner

  # Mapping of Kubernetes Secret Keys to AWS SSM Parameter Store paths
  data:
  - secretKey: db-password
    remoteRef:
      # AWS SSM Parameter Store Key (SecureString)
      # You can create this via:
      # aws ssm put-parameter --name "/production/microservices/db_password" --value "<password>" --type SecureString --region ap-south-1
      key: /production/microservices/db_password
